CHIP="a64"
PROCESSOR_FAMILY="sun50i_a64"
ARCH="arm64"
CROSS_COMPILE="aarch64-linux-gnu-"
UBOOT_DEFCONFIG="armsbc-rwa-a64_defconfig"
KERNEL_DEFCONFIG="armsbc-a64_defconfig"
DEVICE_TREE="sun50i-a64-armsbc-rwa.dts" 
