CHIP="rk3128"
ARCH="arm"
CROSS_COMPILE="arm-linux-gnueabihf-" 
UBOOT_DEFCONFIG="armsbc-dca-rk3128_defconfig"
KERNEL_DEFCONFIG="armsbc-3128_defconfig"
DEVICE_TREE="rk3128-armsbc-dca.dts"
BOARD="armsbc-dca-3128"
